function map=subjectSessionMap
    % function that returns session to keep by subject
    % (some sessions are speed tests, etc.)

    % runs to keep by subject (take all if empty)
    subjects = {'AMC026',...
                'AMC029',...
                'AMC031',...
                'AMC037',...
                'AMC038',...
                'AMC044',...
                'AMC082',...
                'AMC086',...
                'AMC088',...
                'AMC091',...
                'AMC092',...
                'AMC096',...
                'AMC097',...
                'AMC099',...
                'MCJ011',...
                'MCJ014',...
                'BJH006',...
                'BJH007',...
                'BJH008',...
                'BJH011',...
                'BJH012',...
                'BJH016',...
                'SLCH002'...
    };
    sessions = {[];...
                [];...
                [];...
                [];...
                [];...
                [];...
                [2:4];...
                [3:5];...
                [1:2];...
                [2:3];...
                [2:3];...
                [2:3];...
                [2:3];...
                [2:3];...
                [1];...
                [1:2];...
                [2:3];...
                [1:2];...
                [1:2];...
                [1:2];...
                [1:2];...
                [1:2];...
                [1:2]...
    };
    map = containers.Map(subjects,sessions);

end